name: forecast 
base: core22 
adopt-info: forecast
grade: stable 
confinement: strict 
source-code: https://github.com/SalaniLeo/Forecast
issues: https://github.com/soumyaDghosh/forecast-snap/issues
contact: soumyadeepghosh2004@zohomail.in
website: https://github.com/soumyaDghosh/forecast-snap
license: GPL-3.0

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  forecast:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/soumyaDghosh/Forecast.git
    #source-tag: '0.2.2'
    source-depth: 1
    meson-parameters:
      - --prefix=/snap/forecast/current/usr
    override-pull: |
      craftctl default
      pip install --prefix=$CRAFT_PART_INSTALL/usr requests==2.30.0
      pip install --prefix=$CRAFT_PART_INSTALL/usr pytz==2023.3
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/python3' -i $CRAFT_PART_INSTALL/usr/local/bin/*
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/forecast/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      find $CRAFT_PART_INSTALL/meta/gui/icons -type f -not -name 'dev.salaniLeo.forecast*' -exec rm {} + -o -type d -empty -exec rmdir {} +
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done
    parse-info: [usr/share/appdata/dev.salaniLeo.forecast.appdata.xml]
    organize:
      snap/forecast/current: .
      usr/local: usr
      usr/lib/python3: usr/lib/python3.10
    prime:
      - -snap/forecast

slots:
  forecast:
    interface: dbus
    bus: session
    name: dev.salaniLeo.forecast
apps:
  forecast:
    command: usr/bin/forecast
    extensions: [gnome]
    common-id: dev.salaniLeo.forecast
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.10/dist-packages:$PYTHONPATH
    plugs:
      - network
      - network-status
      - network-bind
